import React from "react";
import LoginForm from "Pages/login";
import RegisterForm from "Pages/register";
import Dashboard from "Pages/dashboard";
import ProjectSetting from "Pages/projectSetting";
import CreateProject from "Pages/createProject";
import ProfileForm from "Pages/profileForm";
import Support from "Pages/support";
import ScanResult from "Pages/scanResult";
import ScanResultMisra from "Pages/scanResultMisra";
import IssueDetail from "Pages/issueDetail";
import Users from "Pages/users";
import License from "Pages/license";
import Guide from "Pages/guide";
import UpdateUserForm from "Pages/updateUserForm";
import EmailConfiguration from "Pages/emailConfiguration";
import SourceCode from "Pages/sourceCode";
import DataManagement from "Pages/settings/dataManagement";
import Version from "Pages/version";
import ErrorPage from "Pages/error";
import NotFound from "Pages/404";
import HistoryList from "Pages/historyList";
import DevSetting from "Pages/devSetting";
import AccessToken from "Pages/accessToken";

const routesConfig = [
    {
        name: 'sourceCode',
        internal: false,
        path: '/source-code',
        protected: true,
        needAdmin: false,
        header: false,
        sidebar: false,
        pageComponent: SourceCode,
        enabled: true,
    },
    {
        name: 'scanList',
        internal: true,
        path: '/project/:projectkey/scan-list',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: HistoryList,
        enabled: true,
    },
    {
        name: 'version',
        internal: true,
        path: '/version',
        protected: false,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: Version,
        enabled: true,
    },
    {
        name: 'dev-setting',
        internal: true,
        path: '/dev-setting',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: DevSetting,
        enabled: true,
    },
    {
        name: 'login',
        internal: false,
        path: '/login',
        protected: false,
        needAdmin: false,
        header: false,
        sidebar: false,
        redirect: '/dashboard',
        pageComponent: LoginForm,
        enabled: true,
    },
    {
        name: 'dashboard',
        internal: false,
        path: '/dashboard',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: Dashboard,
        enabled: true,
    },
    {
        name: 'project-setting',
        internal: false,
        path: '/project-setting/:projectKey',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ProjectSetting,
        enabled: true,
    },
    {
        name: 'profile',
        internal: false,
        path: '/profile',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ProfileForm,
        enabled: true,
    },
    {
        name: 'create-project',
        internal: false,
        path: '/create-project',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: CreateProject,
        enabled: true,
    },
    {
        name: 'edit-project',
        internal: false,
        path: '/project-edit/:projectKey',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: CreateProject,
        enabled: true,
    },
    {
        name: 'scan-result',
        internal: false,
        exact: true,
        path: '/project/:projectKey',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ScanResult,
        enabled: true,
    },
    {
        name: 'scan-result-misra',
        internal: false,
        exact: true,
        path: '/misra/project/:projectKey',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ScanResultMisra,
        enabled: true,
    },
    {
        name: 'dsr-scans',
        internal: false,
        exact: true,
        path: '/project/:projectKey/scans',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ScanResult,
        enabled: true,
    },
    {
        name: 'dsr-scans-misra',
        internal: false,
        exact: true,
        path: '/misra/project/:projectKey/scans',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ScanResultMisra,
        enabled: true,
    },
    {
        name: 'dsr-scan',
        internal: false,
        exact: true,
        path: '/project/:projectKey/scan/:scanTaskId',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ScanResult,
        enabled: true,
    },
    {
        name: 'dsr-scan-misra',
        internal: false,
        exact: true,
        path: '/misra/project/:projectKey/scan/:scanTaskId',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ScanResultMisra,
        enabled: true,
    },
    {
        name: 'issue-detail',
        internal: false,
        exact: true,
        path: '/project/:projectKey/scan/:scanTaskId/issue/:issueGroupId',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: IssueDetail,
        enabled: true,
    },
    {
        name: 'support',
        internal: false,
        path: '/support',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: Support,
        enabled: true,
    },
    {
        name: 'data-management',
        internal: false,
        path: '/settings/data-management',
        protected: true,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: DataManagement,
        enabled: true,
    },
    {
        name: 'error',
        internal: false,
        path: '/error',
        protected: false,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: ErrorPage,
        enabled: true,
    },
    {
        name: '404',
        internal: false,
        path: '/not-found',
        protected: false,
        needAdmin: false,
        header: true,
        sidebar: true,
        pageComponent: NotFound,
        enabled: true,
    },
    //admin needed
    {
        name: 'setup',
        internal: false,
        path: '/setup',
        protected: true,
        needAdmin: true,
        header: true,
        sidebar: true,
        pageComponent: Guide,
        render: props => {
            return <Guide {...props} />
        },
        enabled: true,
    },
    {
        name: 'users',
        internal: false,
        path: '/users',
        protected: true,
        needAdmin: true,
        header: true,
        sidebar: true,
        pageComponent: Users,
        enabled: true,
    },
    {
        name: 'license',
        internal: false,
        path: '/license',
        protected: true,
        needAdmin: true,
        header: true,
        sidebar: true,
        pageComponent: License,
        enabled: true,
    },
    {
        name: 'user-update',
        internal: false,
        path: '/user/:login/update',
        protected: true,
        needAdmin: true,
        header: true,
        sidebar: true,
        pageComponent: UpdateUserForm,
        enabled: true,
    },
    {
        name: 'email-config',
        internal: false,
        path: '/email-server-configuration',
        protected: true,
        needAdmin: true,
        header: true,
        sidebar: true,
        pageComponent: EmailConfiguration,
        enabled: true,
    },
    {
        name: 'create-user',
        internal: false,
        path: '/create-user',
        protected: true,
        needAdmin: true,
        header: true,
        sidebar: true,
        pageComponent: RegisterForm,
        enabled: true,
    },
    {
        name: 'access-token',
        internal: false,
        path: '/access-token',
        protected: true,
        needAdmin: true,
        header: true,
        sidebar: true,
        pageComponent: AccessToken,
        enabled: true,
    }
];

export default routesConfig;
